-- Rollback initial schema

BEGIN;

DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS commands CASCADE;
DROP TABLE IF EXISTS work_sessions CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS heartbeats CASCADE;
DROP TABLE IF EXISTS onboarding_tokens CASCADE;
DROP TABLE IF EXISTS admin_sessions CASCADE;
DROP TABLE IF EXISTS machines CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;

DROP TYPE IF EXISTS event_type;
DROP TYPE IF EXISTS command_status;
DROP TYPE IF EXISTS alert_severity;
DROP TYPE IF EXISTS alert_status;

DROP FUNCTION IF EXISTS update_updated_at_column();

COMMIT;
