// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<Record<string, string>>;

export function GetStatus():Promise<main.Status>;

export function InstallAI():Promise<main.Status>;

export function LaunchAI():Promise<main.Status>;

export function OpenInstallFolder():Promise<void>;

export function RefreshManifest():Promise<main.Status>;
