// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallAI() {
  return window['go']['main']['App']['InstallAI']();
}

export function LaunchAI() {
  return window['go']['main']['App']['LaunchAI']();
}

export function OpenInstallFolder() {
  return window['go']['main']['App']['OpenInstallFolder']();
}

export function RefreshManifest() {
  return window['go']['main']['App']['RefreshManifest']();
}

export function StartFlow(arg1) {
  return window['go']['main']['App']['StartFlow'](arg1);
}
